[tools]
# TODO: lest is waiting on some Gargantuan features for support to be included,
# see the ROSS thread
lest = "lest-luau/lest@0.6.0-canary.1"
luau-lsp = "JohnnyMorganz/luau-lsp@1.68.1"
stylua = "JohnnyMorganz/StyLua@2.5.2"
seal = "seal-runtime/seal@0.8.0"
lute = "luau-lang/lute@1.0.0"
